#include "client_doubles.h"
using namespace Packets::Peds;
int main(){
 ModelInfo model;for(auto&ptr:CModelInfo::ms_modelInfoPtrs)ptr=&model;
 CPed local;local.m_nPedType=PED_TYPE_PLAYER1;CWorld::Players[0].m_pPed=&local;CPools::GetPedRef(&local);
 CNetworkPedManager::Init();
 PedSpawn spawn;spawn.pedid=4;spawn.stamp={10,1,1};spawn.ownerid=1;
 PedReplay replay;replay.onFoot.pedid=4;replay.onFoot.stamp={10,1,1};replay.onFoot.healthSnapshot.iHealth=40;replay.onFoot.area=18;replay.onFoot.pos={100,200,30};
 auto creates=nativeCreates;receive(spawn);receive(replay);
 tick+=600000;CNetworkPedManager::ProcessPendingNative();expect(!CNetworkPedManager::GetPed(4)&&nativeCreates==creates&&Deferred().size()==2,"Ten-minute menu wait keeps bounded dormant identity/state without native creation or timeout.");
 gGameState=9;CNetworkPedManager::ProcessPendingNative();expect(!CNetworkPedManager::GetPed(4),"Game state alone cannot bypass completed-script readiness.");
 Events::processScriptsEvent.after.Fire();poolFull=true;tick+=300;CNetworkPedManager::ProcessPendingNative();
 expect(!CNetworkPedManager::GetPed(4)&&Deferred().size()==2,"Actual constructor pool exhaustion retains reliable spawn and state.");
 poolFull=false;modelsAvailable=false;for(auto&i:CStreaming::ms_aInfoForModel)i.m_nLoadState=0;tick+=300;CNetworkPedManager::ProcessPendingNative();
 expect(!CNetworkPedManager::GetPed(4)&&Deferred().size()==2,"Actual model failure retains dormant identity and state.");
 modelsAvailable=true;tick+=300;CNetworkPedManager::ProcessPendingNative();auto*ped=CNetworkPedManager::GetPed(4);
 expect(ped&&ped->m_nPedId==4&&ped->m_generation==10&&ped->m_pPed->m_fHealth==40&&ped->m_pPed->m_nAreaCode==18,"Retry constructs lookupable generation and applies only its retained authoritative state.");
 expect(Deferred().empty(),"Successful native readiness drains retained join replay.");
 auto* actor=ped->m_pPed;int ref=ped->m_nPedPoolRef;CPools::pool.refs.erase(ref);CPools::pool.refs[ref+1]=actor;
 expect(!ped->AcceptState({10,1,2})&&actor->m_fHealth==40,"Same-address recycled full pool reference rejects native state application.");ped->m_nPedPoolRef=ref+1;
 PedReplay driver;driver.mode=2;driver.driver.pedid=4;driver.driver.stamp={10,1,2};driver.driver.pedHealth.iHealth=30;receive(driver);
 expect(Deferred().size()==1&&warps==0,"Missing vehicle defers reliable driver state instead of dropping it.");
 CAutomobile car;CNetworkVehicle networkCar;networkCar.m_pVehicle=&car;CNetworkVehicleManager::vehicle=&networkCar;tick+=300;CNetworkPedManager::ProcessPendingNative();
 expect(Deferred().empty()&&car.m_pDriver==actor&&actor->m_fHealth==30,"Vehicle becoming available later applies original retained driver state.");
 PedReplay passenger;passenger.mode=3;passenger.passenger.pedid=4;passenger.passenger.stamp={10,1,3};passenger.passenger.seatid=2;
 CNetworkVehicleManager::vehicle=nullptr;receive(passenger);expect(Deferred().size()==1,"Missing passenger vehicle remains pending independently of driver state.");
 CNetworkVehicleManager::vehicle=&networkCar;tick+=300;CNetworkPedManager::ProcessPendingNative();expect(car.m_apPassengers[2]==actor&&Deferred().empty(),"Late passenger vehicle applies bounded seat state.");
 // Actual passenger handler must not commit state until native task placement
 // succeeds; an occupied target is never displaced and reliable replay survives.
 CPed occupant(PED_TYPE_PLAYER1);car.m_apPassengers[4]=&occupant;
 passenger.passenger.seatid=4;passenger.passenger.stamp.sequence=4;auto oldWarps=warps;
 receive(passenger);
 expect(car.m_apPassengers[4]==&occupant&&warps==oldWarps&&ped->m_stateSequence==3,"Occupied target seat rejects warp and leaves sequence unconsumed.");
 expect(Deferred().size()==1,"Reliable passenger replay remains pending while target seat is occupied.");
 car.m_apPassengers[4]=nullptr;passengerWarpSucceeds=false;tick+=300;CNetworkPedManager::ProcessPendingNative();
 expect(ped->m_stateSequence==3&&Deferred().size()==1&&car.m_apPassengers[4]==nullptr,"Native passenger task failure retains replay without consuming its sequence.");
 passengerWarpSucceeds=true;tick+=300;CNetworkPedManager::ProcessPendingNative();
 expect(ped->m_stateSequence==4&&Deferred().empty()&&car.m_apPassengers[4]==actor,"Successful retry consumes sequence only after native target placement matches.");
 passenger.passenger.seatid=-1;passenger.passenger.stamp.sequence=5;receive(passenger);
 expect(ped->m_stateSequence==4&&Deferred().empty(),"Malformed retained passenger seat cannot index native array or enter retry queue.");
 AssignPedSyncer assign;assign.pedid=4;assign.stamp={10,2,4};assign.ownerid=0;receive(assign);
 expect(ped->m_bSyncing&&ped->m_ownerEpoch==2,"Actual assignment sets explicit local ownership.");
 receive(assign);expect(ped->m_bSyncing,"Repeated assignment cannot toggle ownership off.");
 assign.ownerid=1;receive(assign);expect(ped->m_bSyncing&&ped->m_ownerId==0,"Same epoch cannot change owner identity.");
 NPCSync::Stamp next;expect(ped->NextState(next)&&next.sequence==5&&next.epoch==2,"New owner continues received state sequence.");
 PedRemove oldRemove;oldRemove.pedid=4;oldRemove.stamp={10,1,3};receive(oldRemove);expect(CNetworkPedManager::GetPed(4)==ped,"Old owner removal cannot erase current epoch.");
 CNetworkPedManager::Clear();gGameState=0;Events::initScriptsEvent.before.Fire();
 spawn.stamp={20,1,0};receive(spawn);replay.onFoot.stamp={20,1,1};receive(replay);
 spawn.stamp={21,1,0};receive(spawn);expect(Deferred().size()==1,"Newer pending spawn supersedes all older lifetime replay.");
 PedRemove removed;removed.pedid=4;removed.stamp={21,1,0};receive(removed);receive(spawn);
 expect(Deferred().empty(),"Pending removal tombstone rejects delayed same-generation spawn.");
 spawn.stamp={20,1,0};receive(spawn);expect(Deferred().empty(),"Older generation cannot resurrect removed pending slot.");
 spawn.stamp={22,1,0};receive(spawn);gGameState=9;Events::processScriptsEvent.after.Fire();tick+=300;CNetworkPedManager::ProcessPendingNative();
 expect(CNetworkPedManager::GetPed(4)&&CNetworkPedManager::GetPed(4)->m_generation==22,"Fresh later generation can reuse tombstoned slot.");
 CNetworkPedManager::Clear();
 // Real hosted creation/token and pin API, before the server knows its slot.
 CPed wave(PED_TYPE_GANG2,MODEL_MALE01);wave.m_matrix=nullptr;CLocalPlayer::m_bIsHost=true;auto*pending=CNetworkPed::CreateHosted(&wave);auto token=pending->m_requestToken;
 expect(pending&&pending->m_nPedType==PED_TYPE_GANG2,"Hosted placement can register without an allocated native matrix and preserves ped metadata.");
 expect(CNetworkPedManager::PinGangWarPedToHost(&wave,true)&&pending->m_bPinned,"Host pin survives unconfirmed native creation.");
 expect(static_cast<PedPin&>(*GetPacketFactory().sent.back()).requestToken==token,"Pending host pin immediately carries the exact creation capability before confirmation.");
 PedConfirm confirm;confirm.tempid=pending->m_nTempId;confirm.requestToken=token+1;confirm.pedid=7;confirm.stamp={40,1,0};confirm.ownerid=0;receive(confirm);
 expect(CNetworkPedManager::m_apTempPeds[pending->m_nTempId]==pending,"Delayed mismatched confirmation cannot consume a reused temporary slot.");
 confirm.requestToken=token;receive(confirm);
 expect(CNetworkPedManager::GetPed(7)==pending&&GetPacketFactory().sent.back()->GetType()==ePacketType::PED_PIN,"Exact token confirmation emits the retained host pin with real identity.");
 CNetworkPedManager::Clear();auto*retry=CNetworkPed::CreateHosted(&wave);
 expect(retry&&retry->m_requestToken>token,"Clear/retry never resets creation token counter.");CNetworkPedManager::Clear();
 auto*dying=CNetworkPed::CreateHosted(&wave);auto deadToken=dying->m_requestToken;auto deadSlot=dying->m_nTempId;
 CNetworkPedManager::HandlePedDestruction(&wave);
 expect(!CNetworkPedManager::m_apTempPeds[deadSlot],"Actual native destructor boundary reclaims unconfirmed temporary wrapper.");
 auto*freshPending=CNetworkPed::CreateHosted(&wave);auto freshToken=freshPending->m_requestToken;
 confirm.tempid=deadSlot;confirm.requestToken=deadToken;confirm.stamp={44,1,0};receive(confirm);
 expect(CNetworkPedManager::m_apTempPeds[deadSlot]==freshPending&&freshPending->m_requestToken==freshToken&&GetPacketFactory().sent.back()->GetType()==ePacketType::PED_REMOVE,"Late old-token confirmation removes only original server lifetime and preserves reused temporary slot.");
 auto&staleRemove=static_cast<PedRemove&>(*GetPacketFactory().sent.back());expect(staleRemove.stamp.generation==44,"Late confirmation cleanup carries old confirmed generation/epoch.");
 CPools::pool.refs.erase(CPools::GetPedRef(&wave));CNetworkPedManager::RemoveInvalidPeds();
 expect(!CNetworkPedManager::m_apTempPeds[deadSlot],"Pool-invalid unconfirmed actor is reclaimed without waiting forever for server capacity/model acceptance.");
 CPools::GetPedRef(&wave);CNetworkPedManager::Clear();
 // Deferred work remains monotonic while a menu/model/pool prevents binding.
 gGameState=0;Events::initScriptsEvent.before.Fire();spawn.stamp={50,1,0};receive(spawn);
 assign.pedid=4;assign.stamp={50,3,8};assign.ownerid=0;receive(assign);
 auto older=assign;older.stamp.epoch=2;older.ownerid=1;receive(older);
 oldRemove.stamp={50,2,8};receive(oldRemove);
 expect(Deferred().size()==2,"Older queued assignment/removal cannot overwrite a newer pending ownership epoch.");
 gGameState=9;Events::processScriptsEvent.after.Fire();tick+=300;CNetworkPedManager::ProcessPendingNative();
 expect(CNetworkPedManager::GetPed(4)&&CNetworkPedManager::GetPed(4)->m_ownerEpoch==3&&CNetworkPedManager::GetPed(4)->m_bSyncing,"Dormant native binding adopts the highest confirmed pending epoch.");
 CNetworkPedManager::Clear();
 std::cout<<checks<<" assertions, "<<failures<<" failures\n";return failures?1:0;
}
